-- Tabela de pedidos: vendas, carrinhos abandonados e controle de envio.
-- Rode este script uma vez no SQL Editor do Supabase (dashboard do projeto).
--
-- Cada linha nasce como "abandonado" assim que o cliente preenche e-mail no
-- carrinho, e vai sendo atualizada (mesma linha, pela "referencia") conforme
-- o pagamento avança: aguardando_pagamento -> pago, ou falhou/cancelado.
-- Pedidos combinados no WhatsApp entram direto como "combinado_whatsapp".

create table if not exists "Pedidos" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  referencia text not null unique,
  origem text not null,               -- 'asaas_pix' | 'asaas_cartao' | 'paypal' | 'whatsapp'
  status text not null default 'abandonado',
  -- status possiveis: abandonado | aguardando_pagamento | em_analise | pago | falhou | cancelado | combinado_whatsapp
  cliente_nome text,
  cliente_email text,
  cliente_telefone text,
  cliente_cpf text,
  endereco jsonb,
  itens jsonb,
  subtotal numeric,
  frete numeric,
  frete_servico_id text,               -- id do servico do Melhor Envio escolhido no checkout (necessario p/ gerar etiqueta)
  frete_nome text,
  total numeric,
  gateway_id text,                    -- id do pagamento na Asaas ou da order no PayPal
  pago_em timestamptz,
  envio_status text not null default 'aguardando',
  -- envio_status possiveis: aguardando | etiqueta_gerada | postado | entregue | cancelado
  rastreio_codigo text,
  etiqueta_url text,
  melhor_envio_id text,
  observacoes text
);

create index if not exists pedidos_status_idx on "Pedidos" (status);
create index if not exists pedidos_created_idx on "Pedidos" (created_at desc);
create index if not exists pedidos_gateway_idx on "Pedidos" (gateway_id);

alter table "Pedidos" enable row level security;

-- Mesmo nivel de acesso que "Produtos"/"Avaliacoes" ja tem hoje (a chave anon
-- e usada tanto pelo site quanto pelo admin.html e pelas funcoes do Netlify
-- para ler/gravar direto). Sem isso, os inserts das funcoes de checkout e o
-- painel admin.html seriam bloqueados pelo RLS.
drop policy if exists "Pedidos anon all" on "Pedidos";
create policy "Pedidos anon all" on "Pedidos"
  for all
  to anon
  using (true)
  with check (true);
